### ISSUE TITLE
Changelog Link on Release Blog Wrong

### ISSUE THREAD

**Issue by lbussy** [OctoPrint/OctoPrint#4134]
### The problem

The changelog for the [blog notification](https://octoprint.org/blog/2021/05/10/new-release-1.6.1/) points to [version 1.5.3](https://github.com/OctoPrint/OctoPrint/releases/tag/1.5.3) instead of 1.6.1.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.6.1

### Operating system running OctoPrint

Nonw

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
[Wrong issue tracker](https://github.com/OctoPrint/octoprint.org/issues) (not an OctoPrint issue but an issue with a post on octoprint.org) but fixed by the above commit, should be live soon. Thanks for the heads-up.
